/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    'news-articles': NewsArticle;
    'team-members': TeamMember;
    fixtures: Fixture;
    'profile-picture': ProfilePicture;
    'opponent-picture': OpponentPicture;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'news-global': NewsGlobal;
    'get-in-touch': GetInTouch;
    'about-section': AboutSectionGlobal;
    'fixtures-section': FixturesSectionGlobal;
    'team-members-section': TeamMembersSectionGlobal;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface NewsGlobal {
  id: string;
  featuredNews?: (string | NewsArticle)[] | null;
  globalType?: 'news-global';
}

export interface NewsArticle {
  id: string;
  title: string;
  date: string;
  content: string;
  image: string | Media; // Assuming a 'Media' type is defined in payload-types.ts
  category:
    | 'announcement'
    | 'team-news'
    | 'player-spotlight'
    | 'match-report'
    | 'sponsorship'
    | 'event'
    | 'match'
    | 'common'
    | 'training';
  updatedAt: string;
  createdAt: string;
}

export interface TeamMember {
  id: string;
  name: string;
  position:
    | 'Wing'
    | 'Scrum Half'
    | 'Fly Half'
    | 'Center'
    | 'Full Back'
    | 'Prop'
    | 'Hooker'
    | 'Lock'
    | 'Flanker'
    | 'Founder'
    | 'co-Founder'
    | 'Coach'
    | 'Fitness Coach'
    | 'Team Manager';
  experience: number;
  image: string | ProfilePicture; // Relation to ProfilePicture
  order: number;
  updatedAt: string;
  createdAt: string;
}

export interface Fixture {
  id: string;
  date: string;
  time: string;
  modifedTitle?: string | null;
  opponent: string;
  image: string | OpponentPicture;
  location: string;
  status: 'Upcoming' | 'Won' | 'Lost' | 'Draw';
  result?: {
    ourScore?: number | null;
    opponentScore?: number | null;
  } | null;
  updatedAt: string;
  createdAt: string;
}

export interface ProfilePicture {
  id: string;
  Name?: string | null;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}

export interface OpponentPicture {
  id: string;
  'Opponent Name': string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    } | null;
  } | null;
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "get-in-touch".
 */
export interface GetInTouch {
  id: string;
  email: string;
  phone: string;
  address: string;
  instagram?: string | null;
  whatsapp?: string | null;
  twitter?: string | null;
  globalType?: 'get-in-touch';
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-section".
 */
export interface AboutSectionGlobal {
  id: string;
  description?: string | null;
  firstBoxTitle?: string | null;
  firstBoxDescription?: string | null;
  secondBoxTitle?: string | null;
  secondBoxDescription?: string | null;
  thirdBoxTitle?: string | null;
  thirdBoxDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published');
  globalType?: 'about-section';
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fixtures-section".
 */
export interface FixturesSectionGlobal {
  id: string;
  featuredFixtures?: (string | Fixture)[] | null;
  updatedAt: string;
  createdAt: string;
  globalType?: 'fixtures-section';
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members-section".
 */
export interface TeamMembersSectionGlobal {
  id: string;
  featuredTeamMembers?: (string | TeamMember)[] | null;
  updatedAt: string;
  createdAt: string;
  globalType?: 'team-members-section';
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}

